### PR TITLE
feat: enhance docker setup

### LINKED ISSUE #445: Enhance Docker Setup
# Enhance Docker Setup

#### Description:
We need to create Docker images for the Laravel backend (PHP service only) and the Nuxt.js frontend. Additionally, we need to set up Docker Compose configurations to orchestrate these services along with necessary supporting services like the database, Redis, Minio, and Nginx. The setup should be easy to use and suitable for both production and local development environments. Finally, update the GitHub CI workflow to publish the Docker images.

#### Tasks:

1. **Create Docker Images:**
   - **Laravel Backend:** Create a Dockerfile for the Laravel application (PHP service only).
   - **Nuxt.js Frontend:** Create a Dockerfile for the Nuxt.js application.

2. **Docker Compose Setup:**
   - Create a `docker-compose.yml` file for production that combines the Laravel backend, Nuxt.js frontend, Nginx, and additional services (Postgres, Redis, Minio).
   - Create a `docker-compose.dev.yml` file for local development with the same services, but configured for a development environment (e.g., enabling hot reloading for Nuxt.js).

3. **Update GitHub CI Workflow:**
   - Update the GitHub Actions workflow to build and publish the Docker images for the Laravel and Nuxt.js applications.

#### Requirements:

1. **Dockerfile for Laravel Backend:**
   - Build a Docker image for the Laravel application, excluding Nginx (to be handled in Docker Compose).
   - Use Docker environment variables for configuration.

2. **Dockerfile for Nuxt.js Frontend:**
   - Build a Docker image for the Nuxt.js application.
   - Use Docker environment variables for configuration.

3. **Docker Compose Configuration:**
   - **Production:** Define a `docker-compose.yml` file for production that includes services for Laravel, Nuxt.js, Nginx, Postgres, Redis, and Minio. Ensure services are properly networked and can communicate with each other.
   - **Development:** Define a `docker-compose.dev.yml` file for local development. Configure the Nuxt.js service to support hot reloading and ensure that the setup is optimized for a development environment.
   - Use Docker environment variables to configure each service.

4. **GitHub CI Workflow:**
   - Modify the existing CI workflow to build Docker images for both the Laravel backend and Nuxt.js frontend.
   - Ensure the workflow publishes the Docker images to the appropriate Docker registry.

#### Additional Notes:

- The setup should be easy to use, even for those not familiar with Docker.
- Provide clear and concise documentation for setting up and using the Docker Compose configurations for both production and development.
- Test the setup to ensure it works seamlessly for both development and production environments.
- Please also update the readme with explanations on how to run the project (both for production and local development)

### PR DESCRIPTION
**Pull request by varshith257**
Fixes #445 
/claim #445 

Tasks:

- [x] Dockerfile for Laravel Backend
- [x] Dockerfile for Nuxt.js Frontend
- [ ] Docker Compose Configuration
- [ ] GitHub CI Workflow

## Summary by CodeRabbit

- **New Features**
  - Introduced Docker support for backend and frontend applications.
  - Backend: PHP application running in an Alpine-based PHP-FPM container, installing necessary dependencies and performing database migrations.
  - Frontend: Node.js environment for building and serving the application.

### CODE REVIEW

**Comment by varshith257** [comment]
@ezhil56x Why can't we run docker files individually to test their behavior?

docker build -f Dockerfile.backend -t opnform-backend .

Yes, I agree with you for compose to test the whole application

**Comment by ezhil56x** [comment]
php-fpm cannot handle http requests, it's just a process manager which requires additional web server to handle http request 

> @ezhil56x Why can't we run docker files individually to test their behavior?
> 
> ```
> docker build -f Dockerfile.backend -t opnform-backend .
> ```
> 
> Yes, I agree with you for compose to test the whole application

**Comment by varshith257** [comment]
Ok then will update soon the docker-compose too

**Comment by JhumanJ** [comment]
> Fixes #445 /claim #445
> 
> Tasks:
> 
> * [x]  Dockerfile for Laravel Backend
> * [x]  Dockerfile for Nuxt.js Frontend
> * [ ]  Docker Compose Configuration
> * [ ]  GitHub CI Workflow
> 
> ## Summary by CodeRabbit
> * **New Features**
>   
>   * Introduced Docker support for backend and frontend applications.
>   * Backend: PHP application running in an Alpine-based PHP-FPM container, installing necessary dependencies and performing database migrations.
>   * Frontend: Node.js environment for building and serving the application.

Hi @varshith257 and thanks for this. I can only see the the 2 docker images - not the compose ones, is this a draft?

**Comment by varshith257** [comment]
@JhumanJ Wil push docker- compose very soon

**Comment by flece** [comment]
wow 30 lines of code ...copy/pasted from somewhere..without any knowledge in the field. uses "apt" on an Alpine-Image ... even the Bot knows it better. Let alone Multistage Builds ... this is just a quick moneygrab.

@JhumanJ maybe you remove the bounty...it just pulls in the wrong ppl.

**Comment by varshith257** [comment]
Hey @flece Thanks for info, I hadn't gone through it and tested because facing issues with docker in my local. It have to be php:8.3-fpm , I think It have been replaced alpine wrong there. I have no time for now as my university semester exams are ongoing. My exams will take a week to complete. Maybe You can close this PR if you'd like to. 

And for my experience with docker I have done internship on building dockeee configuration from scratch in production environments and also contributed in OS orgs for docker setup (I think this you can be verified)

But thanks for pinpointing it again!

**Pull request closed without merging**
