### PR TITLE
fix: navbar help link

### PR DESCRIPTION
**Pull request by jeffrey-zang**
#76

### CODE REVIEW

**Comment by jeffrey-zang** [comment]
btw what are you guys deploying the website with? just curious

**Review by JhumanJ — CHANGES_REQUESTED** [review]
Thanks for this! It wasn't the case here but we try to use `links.php` config file to centralize all links. You can then use `window.config.links.help_url` in the javascript to consume it. Could you please make the change? 🙏

btw, we use https://vapor.laravel.com/ for deployments

**Comment by jeffrey-zang** [comment]
@JhumanJ not sure if I did this right, does it look ok?

**Review by JhumanJ — APPROVED** [review]
Great, thank you!

**Pull request merged**
