### PR TITLE
feat(s3-aws): Implement use_path_style_endpoint for Minio usage 

### PR DESCRIPTION
**Pull request by valentin2105**
Hello

I tryed to use the S3 Storage with Minio (open-source S3 platform), but the `aws path style` is problematic.

It would be nice if we can tweak that from ENV VAR.

Thank you

### CODE REVIEW

**Review by JhumanJ — CHANGES_REQUESTED** [review]
Thanks for the PR. That works for me, but can you make it true by default to keep the preserve behavior and avoid breaking existing deployments?

**Comment by valentin2105** [comment]
@JhumanJ the change is done.

**Review by JhumanJ — APPROVED** [review]

**Review by JhumanJ — APPROVED** [review]
Great thanks!

**Comment by JhumanJ** [comment]
Merged, thank you!

**Pull request merged**
