### PR TITLE
fix: Vue3 Query Builder - Logic Editor

### LINKED ISSUE #250: Vue3 Query Builder - Logic Editor
Hi,
We're in the process of migrating the project to version 3 of Vue. For the field logic editor, we [use this package](https://github.com/rtucek/vue-query-builder) who only has support for vue 2. They aren't too many files in this package, so I believe that it shouldn't be too hard to fork it and to add support for Vue3.

## How to reproduce the compatibility errors
- Check out `vue-3` branch, `npm install`, `npm run dev`
- Open the form editor in the browser
- Click on the blue cog to open field settings for any of the fields
- Open console to see trigger warnings (still working since on `vue-3` branch we still run `@vue/compat`)

## Example errors:
```
[Vue warn]: onActivated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
  at <QueryBuilderGroup config= {operators: Array(2), rules: Array(3), colors: Array(6)} query= 
```
or 
```
[Vue warn]: onUpdated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
  at <QueryBuilderGroup config= 
```

## Acceptance criteria
- We need an open-source fork of this `vue-query-builder` package
- And a PR to the `vue-3` branch, replacing the `rtucek/vue-query-builder` dependency with the new query builder, essentially fixing these issues!

Thank you!

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #250
/claim #250

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
package: https://www.npmjs.com/package/query-builder-vue-3
repo: https://github.com/rishi-raj-jain/query-builder-vue-3

**Comment by rishi-raj-jain** [comment]
recording of the same that it works 👇🏻

https://github.com/JhumanJ/OpnForm/assets/46300090/4c27aae4-5273-4f0c-8fbc-5a7c5c5fafeb

**Comment by rishi-raj-jain** [comment]
In case you want to test it, do the following:

```
rm -rf node_modules
npm install
npm run dev
```

**Comment by rishi-raj-jain** [comment]
Btw, I should say it here explicitly I think, I am more than happy to split the bounty with @kwesterfeld2 for their work.

**Review by JhumanJ — APPROVED** [review]

**Comment by JhumanJ** [comment]
Thanks for that! I think it's fair to split with @kwesterfeld2! 
Can you please check the tests? Although it's working locally for me, pipeline is broken @rishi-raj-jain

**Pull request merged**
